### ISSUE TITLE
Remove deprecated paragraphs

### ISSUE THREAD

**Issue by magjarvis** [ATLAS-Illinois/Illinois-Framework-Core#6]
No longer using Colored text block, Two-column text, Text with image and header. Replace with Rich Text modifications

**Comment by wrg20** [comment]
I have started working on some of the rich text modifications for a 2 column.

**Comment by trubach** [comment]
@magjarvis  - it looks like you created a new paragraph type with the machine name "cta". There's also a "call_to_action" paragraph type that looks like we should remove. Is that your impression as well?

**Comment by magjarvis** [comment]
@trubach yes, the ones i made should just be 'cta' or 'cta_narrow'
