### ISSUE TITLE
unrecognized field paragraph types node.spotlight.field_paragraph et al

### ISSUE THREAD

**Issue by zeiders** [ATLAS-Illinois/Illinois-Framework-Core#69]
I got the following error running drush cr:

`>drush cr
 [warning] The "field_paragraph" at "node:blog" references the "paragraph:acc_content" entity type that does not exist. Please take action. ResourceTypeRepository.php:465
 [warning] The "field_paragraph" at "node:news" references the "paragraph:acc_content" entity type that does not exist. Please take action. ResourceTypeRepository.php:465
 [warning] The "field_paragraph" at "node:spotlight" references the "paragraph:acc_content" entity type that does not exist. Please take action. ResourceTypeRepository.php:465
 [success] Cache rebuild complete.`

I believe these are related to the files:

- web\modules\contrib\illinois_framework_core\config\install\field.field.node.blog.field_paragraph.yml
- web\modules\contrib\illinois_framework_core\config\install\field.field.node.news.field_paragraph.yml
- web\modules\contrib\illinois_framework_core\config\install\field.field.node.spotlight.field_paragraph.yml

and possibly

-web\modules\contrib\illinois_framework_core\config\install\field.field.paragraph.contact.field_contact_content.yml
- web\modules\contrib\illinois_framework_core\config\install\field.field.paragraph.icon_row.field_icon_row_content.yml

In these files I believe "acc_content" should be "accordian_content".
I can make the warnings go away by going into "Content types" -> "blog|news|spotlight" -> "Manage Fields" and then editing paragraph field's fields such that the "Accordian Row" paragaph is checked and then selecting save.

**Comment by trubach** [comment]
Thanks for submitting this issue, @zeiders. I really appreciate that you included all the file paths that you found the orphaned config. 

I've created PR #71 that should address the issue, and the changes will be included in the next release.
